### PR TITLE
Updated FAQ to point to docs

### PR DESCRIPTION
**Pull request by dlepow**

### CODE REVIEW

**Comment by dlepow** [comment]
@sajayantony and team - also please update aka.ms/acr/faq to point to https://docs.microsoft.com/azure/container-registry/container-registry-faq (or add me as owner to the link and I will update it).

Thanks!

**Comment by sajayantony** [comment]
Added you as the link owner. Feel free to update once this is published. 
Thanks for helping @dlepow

**Comment by dlepow** [comment]
@sajayantony  - FAQ published at https://docs.microsoft.com/en-us/azure/container-registry/container-registry-faq and aka.ms link updated.
Can you please merge this PR? Thx.

**Comment by dlepow** [comment]
@sajayantony - I believe I rebased my local branch correctly and this can now be merged. If this still can't be merged, please close and I'll submit a new PR. Apologies for churn. Shouldn't have been working in a stale local branch.

**Pull request merged**
